### ISSUE TITLE
Thorium won't open the second time you use it.

### ISSUE THREAD

**Issue by ghost** [Alex313031/Thorium-Android#59]
**System Details**
 - OS: Android 13 (Realme C51)
 - Thorium Version: M124.0.6367.218

**Problem**
I just installed Thorium and opened it, closed it, and then it crashes. The app somehow crashes the second time you open it and so on and there's no way to fix it. I tried clearing cache, force stopping and reinstallation and to no avail.

**Screenshots**
Can't send apparently the file was too big. So basically the video shows that I installed the app, opened it, clicked "Use without an account", closed it and boom, app won't open.

**Additional Context**
I chose "Use without an account" because when I chose "Use with an account", the app says email already exists on device. I don't think it has any connection to the problem, though I'll try fixing it on my end and see if it works.

**Comment by gz83** [comment]
Are you using arm32 or arm64 version?

**Comment by sabamdarif** [comment]
> Are you using arm32 or arm64 version?

i have the same problem , me using arm64 on android 14

**Comment by gz83** [comment]
Please try arm32 version

@sabamdarif

**Comment by sabamdarif** [comment]
> Please try arm32 version
> 
> @sabamdarif

same problem , is there any way to capture specifically thorium's log so i can send it here

**Comment by sabamdarif** [comment]
> Please try arm32 version
> 
> @sabamdarif

ONLY THORIUM :- 

[log_2024_05_31_22_27_51-only-thorium.log](https://github.com/user-attachments/files/15516684/log_2024_05_31_22_27_51-only-thorium.log)

THORIUM AND SOME SYSTEM LOG:- 

[log_2024_05_31_22_25_03.log](https://github.com/user-attachments/files/15516695/log_2024_05_31_22_25_03.log)

**Comment by alanbjoseph** [comment]
same issue

running LineageOS 21 - Android 14

**Comment by ghost** [comment]
> Are you using arm32 or arm64 version?

I'm using "Thorium_Public-arm64".

**Comment by gz83** [comment]
Please try arm32 version

@sheesh3178

**Comment by gz83** [comment]
Will version 123 run normally on your device?

@sheesh3178 @sabamdarif @alanbjoseph

**Comment by alanbjoseph** [comment]
arm32 - not working
version 123 also not working

LineageOS 21 running on Motorola Edge 30 (dubai)

**Comment by gz83** [comment]
Do you have Google services installed on your system?
@alanbjoseph

**Comment by alanbjoseph** [comment]
NO google services installed.
will it not work without it?

**Comment by gz83** [comment]
Yes, it is recommended to install Google services

@alanbjoseph

**Comment by alanbjoseph** [comment]
oh, it's a no-go for if that is the case.
sorry.
i'm keeping my device de-googled for obvious purposes.

how about others who reported the same issue?
@sheesh3178 @sabamdarif 
do they have google services installed?

**Comment by sabamdarif** [comment]
> oh, it's a no-go for if that is the case. sorry. i'm keeping my device de-googled for obvious purposes.
> 
> how about others who reported the same issue? @sheesh3178 @sabamdarif do they have google services installed?

yes but also don't work

**Comment by Indianb0y016** [comment]
Also happening to me. 
Both versions of thorium.

Android 14, Pixel 8 with Gapps installed

**Comment by sabamdarif** [comment]
> Please try arm32 version
> 
> @sheesh3178

It's only happped in android 14 , in my another device with android 11 it work fine

**Comment by sabamdarif** [comment]
Could it be the problem @gz83 


time: 1717765042177
msg: java.lang.UnsatisfiedLinkError: No implementation found for void J.N.MSkFYnu9(long, int, int, int[], int, long) (tried Java_J_N_MSkFYnu9 and Java_J_N_MSkFYnu9__JII_3IIJ) - is the library loaded, e.g. System.loadLibrary?
stacktrace: java.lang.UnsatisfiedLinkError: No implementation found for void J.N.MSkFYnu9(long, int, int, int[], int, long) (tried Java_J_N_MSkFYnu9 and Java_J_N_MSkFYnu9__JII_3IIJ) - is the library loaded, e.g. System.loadLibrary?
	at J.N.MSkFYnu9(Native Method)
	at org.chromium.components.safe_browsing.SafeBrowsingApiBridge.startUriLookupBySafeBrowsingApi(chromium-Thorium_Public.apk-stable-636721800:13)
	at Kw.run(chromium-Thorium_Public.apk-stable-636721800:484)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by gz83** [comment]
I can use Thorium on Lineages 21. It may be related to some user configuration or some problems in upstream.

@sabamdarif

**Comment by ghost** [comment]
Sorry for the late reply @gz83 

Both arch (64 and 32-bit) for 124 doesn't work, and 123 works normally.

I have Google services installed as this is stock OS. No modifications were done in this phone.

**Comment by alanbjoseph** [comment]
Mulch browser from the DivestOS fdroid repository works just fine.
What is the difference between these two that causes the trouble in Thorium?

**Comment by gnulab-id** [comment]
I am facing the same issue. Samsung Galaxy Z Fold 5 using Android 14.

**Comment by midzer** [comment]
I've accidently uninstalled Thorium, reinstalled it and experiencing the same issue on Android 11, LineageOS, arm32 version.

Even with https://microg.org/ installed it's not working any more.

**Comment by GEAR-IT-UP** [comment]
Same issue. 

I have just downloaded the the latest version for the first time on S24 Ultra. First login is normal. If I close it, it crashes. If I open it again, the phone will give a notification to put it to deep sleep due to the app crashes. 

Solution wise: if I clear all data from the app, it will open and launch correctly. However, the next opening and same story as above. 

When I attempt to login, it tells me "this account is already on this device" type error. As if it wants me to add a new account. I am not sure if this is a setting of something on my phone.

hope this helps?

**Comment by CaiMiao** [comment]
[org.chromium.thorium_2024-08-19T13_19_54.768.log](https://github.com/user-attachments/files/16660254/org.chromium.thorium_2024-08-19T13_19_54.768.log)

approve this quote as same issue occurs on my end.
i have 2 device with google services encounters the problem.

> Could it be the problem @gz83
> 
> time: 1717765042177 msg: java.lang.UnsatisfiedLinkError: No implementation found for void J.N.MSkFYnu9(long, int, int, int[], int, long) (tried Java_J_N_MSkFYnu9 and Java_J_N_MSkFYnu9__JII_3IIJ) - is the library loaded, e.g. System.loadLibrary? stacktrace: java.lang.UnsatisfiedLinkError: No implementation found for void J.N.MSkFYnu9(long, int, int, int[], int, long) (tried Java_J_N_MSkFYnu9 and Java_J_N_MSkFYnu9__JII_3IIJ) - is the library loaded, e.g. System.loadLibrary? at J.N.MSkFYnu9(Native Method) at org.chromium.components.safe_browsing.SafeBrowsingApiBridge.startUriLookupBySafeBrowsingApi(chromium-Thorium_Public.apk-stable-636721800:13) at Kw.run(chromium-Thorium_Public.apk-stable-636721800:484) at java.lang.Thread.run(Thread.java:1012)

**Comment by CaiMiao** [comment]
the problem does not mitigate on latest 126 release

**Comment by midzer** [comment]
According to changelog, it should be fixed:

> Fixed crashing on fresh install

**Comment by CaiMiao** [comment]
hell nope.
[org.chromium.thorium_2024-08-24T01_16_01.523.log](https://github.com/user-attachments/files/16731875/org.chromium.thorium_2024-08-24T01_16_01.523.log)

**Comment by GEAR-IT-UP** [comment]
Can confirm has not fixed the issue on latest recent release. Same issue. I've also checked this on a new s24 ultra install and again failed.

**Comment by gnulab-id** [comment]
Thorium 121.0.6167.204 works fine on Pixel 7 Pro.
Thorium 126.0.6478.246 exhibits the same as the complains above on Samsung Fold Z 5.

I don't dare to try installing it on Pixel 7 Pro.

**Comment by RpxdYTX** [comment]
I just found out that trying to open it normally either directly or by pressing a url in another app when in the last time the app was used it got vlosed with 0 tabs open, it crashes, which may relate to this issue.
By using the open new tab option in the app context bar or the widget (or simply not closing everything before exiting) is a workaround if this also happens to be your case.

**Comment by RpxdYTX** [comment]
Nvm, it seems to crash on just opening links too, I'll rollback even further just to not experience this anymore

**Comment by RpxdYTX** [comment]
Aprils release (123) seems unaffected, you can try downgrading the app through adb (to prevent losing data, specially since sync isn't a thing in android)

**Comment by Brauhhhh** [comment]
Same problem here and it's super annoying 😭

**Comment by Dranick** [comment]
Android version:16
One UI: 8

Public_arm32 doesn't work, public_arm64 crashes on sencond start; it also fails to use the existing Google account thus it proposes to add an account to the device and will subsequently fail to add an already existing account -> this is on the initial, first run.

**Comment by RpxdYTX** [comment]
Alex previously stated that there's no way to sync google accounts on the
android app before, I'm not sure if this situation is still true. As for
the other problems, they should have their own dedicated issues to make it
easier to refer to (and fix) them.

Em seg., 17 de nov. de 2025, 10:50, Nick Dragomir ***@***.***>
escreveu:
